### ISSUE TITLE
Login/Logout Button nach ein bisschen nach rechts verschoben

### ISSUE THREAD

**Issue by RebGe** [jessicaroth/My-own-Cookbook#16]
Vermutlich liegt das daran, dass er von links positioniert wurde, habs mit rechts versucht, hat aber nicht geklappt

**Comment by jessicaroth** [comment]
Habs jetzt weiter nach links verschoben (5%) müsste jetzt eigentlich klappen

**Comment by jessicaroth** [comment]
Habs jetzt auch fancy hinbekommen
