### ISSUE TITLE
Buttons rechts oben nicht funktionsfähig

### ISSUE THREAD

**Issue by jessicaroth** [jessicaroth/My-own-Cookbook#9]
aktuelles Problem: Button funktioniert bei Firefox nicht

**Comment by RebGe** [comment]
Bei mir gehts auch nicht im InternetExplorer, Log-In passiert auch nichts

**Comment by jessicaroth** [comment]
Alles gefixt, eventuell noch kontrolle auf jeder seite ob button geht
